NUM_KEYS = 10000

DB_FILE_FF = "ff.txt"
DB_FILE_FF_INDEX = "ff_index.txt"
RECORD_WIDTH = 10
NUM_UPDATES_FF = 10000

DB_FILE_SQLITE = "sqlite3.db"
NUM_UPDATES_SQLITE = 10000

MYSQL_CONFIG_FILE = "mysql-config.json"
NUM_UPDATES_MYSQL = 10000